# Generated by Django 3.0.8 on 2021-01-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unicastIP', models.CharField(max_length=15)),
                ('maxUniverses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universeType', models.CharField(choices=[('ctrlIn', 'Control Input'), ('consoleIn', 'Console Input'), ('pixelIn', 'Pixel Input'), ('pixelOut', 'Pixel Output')], default='pixelIn', max_length=13)),
                ('universeNumber', models.IntegerField()),
                ('multicast', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pixel',
            name='pixelType',
            field=models.CharField(choices=[('RGB', 'RGB'), ('RGBW', 'RGBW')], default='RGB', max_length=4),
        ),
    ]
