# Generated by Django 3.0.8 on 2021-01-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_auto_20210118_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='consoleEnableChannel',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
