# Generated by Django 3.0.8 on 2021-01-20 01:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_appsettings_consoleenablechannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel',
            name='fixtureNum',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='inputAddress',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(512)]),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='inputUniverse',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='outputAddress',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(512)]),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='outputUniverse',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)]),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='pixelNum',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
