# Generated by Django 3.0.8 on 2021-01-26 04:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0006_auto_20210126_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='universe',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='universe',
            name='pixelOutUni',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(512)]),
        ),
    ]
