# Generated by Django 3.0.8 on 2021-02-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0007_auto_20210126_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='outputPriority',
            field=models.IntegerField(default=100),
        ),
    ]
